name: portfolio
description: A new Flutter project.
publish_to: none
version: 1.0.0+1
environment:
    sdk: '>=2.3.0 <3.0.0'
dependencies:
    flutter:
        sdk: flutter
    
    provider_architecture: ^1.0.3
    responsive_builder: ^0.1.4
    provider: ^3.2.0
    logger: ^0.7.0+2
    get_it: ^3.0.3
    equatable: ^1.0.1
    google_fonts:
    simple_animations: ^2.2.1
    supercharged:
    page_transition: ^1.1.6
    flutter_svg:
    flutter_staggered_grid_view: ^0.3.2
    flutter_web: any
    flutter_web_ui: any
    animated_text_kit: ^2.2.0
    http:
    url_launcher:
    url_launcher_web: ^0.1.0
    fluro: ^1.6.3
    carousel_slider: ^2.2.1


dev_dependencies:
    flutter_test:
        sdk: flutter
    # Enables the `pub run build_runner` command
    build_runner:
  # Includes the JavaScript compilers
    build_web_compilers: ^2.11.0

dependency_overrides:
  flutter_web:
    git:
      url: https://github.com/flutter/flutter_web
      path: packages/flutter_web
  flutter_web_ui:
    git:
      url: https://github.com/flutter/flutter_web
      path: packages/flutter_web_ui

flutter:
    uses-material-design: true


  # To add assets to your application, add an assets section, like this:
assets:
    - assets/
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
      
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
      
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
      
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages